INSERT INTO MY_TABLE(SCRIPT) VALUES ('CREATE USER IF NOT EXISTS "B2181740" SALT ''dc619dee4941845f'' HASH ''28fb6ce9ff1ea4407aaf40e94c3909efc5780de8700e64c39334f055cc44214a'' ADMIN;');
INSERT INTO MY_TABLE(SCRIPT) VALUES ('CREATE CACHED TABLE "PUBLIC"."ACCOUNT"(
    "ID" VARCHAR(8) NOT NULL,
    "NAME" VARCHAR(32) NOT NULL,
    "ROLL" VARCHAR(8) NOT NULL,
    "GRADE" VARCHAR(8) NOT NULL,
    "CLASS" VARCHAR(8) NOT NULL,
    "DEPARTMENT" VARCHAR(16) NOT NULL,
    "PASSWORD" VARCHAR(32) NOT NULL
);');
INSERT INTO MY_TABLE(SCRIPT) VALUES ('ALTER TABLE "PUBLIC"."ACCOUNT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("ID");');
INSERT INTO MY_TABLE(SCRIPT) VALUES ('-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ACCOUNT;');
INSERT INTO MY_TABLE(SCRIPT) VALUES ('CREATE CACHED TABLE "PUBLIC"."LECTURE_INFO"(
    "ID" VARCHAR(8) NOT NULL,
    "LECTURE_NAME" VARCHAR(16) NOT NULL,
    "RESPONSIBLE" VARCHAR(32) NOT NULL,
    "DEPARTMENT" VARCHAR(16) NOT NULL,
    "GRADE" VARCHAR(4) NOT NULL,
    "SESSION" VARCHAR(4),
    "TYPE" VARCHAR(4)
);');
INSERT INTO MY_TABLE(SCRIPT) VALUES ('ALTER TABLE "PUBLIC"."LECTURE_INFO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_EA" PRIMARY KEY("ID");');
INSERT INTO MY_TABLE(SCRIPT) VALUES ('-- 0 +/- SELECT COUNT(*) FROM PUBLIC.LECTURE_INFO;');
INSERT INTO MY_TABLE(SCRIPT) VALUES ('CREATE CACHED TABLE "PUBLIC"."CREDIT_STATUS"(
    "ID" VARCHAR(8) NOT NULL,
    "LECTURE_INFO_ID" VARCHAR(8) NOT NULL
);');
INSERT INTO MY_TABLE(SCRIPT) VALUES ('ALTER TABLE "PUBLIC"."CREDIT_STATUS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("ID", "LECTURE_INFO_ID");');
INSERT INTO MY_TABLE(SCRIPT) VALUES ('-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CREDIT_STATUS;');
INSERT INTO MY_TABLE(SCRIPT) VALUES ('CREATE CACHED TABLE "PUBLIC"."LECTURE_TIME"(
    "ID" VARCHAR(8) NOT NULL,
    "LECTURE_INFO_ID" VARCHAR(8) NOT NULL,
    "START_DATE" DATE NOT NULL,
    "START_TIME" TIME NOT NULL,
    "START_WEEK" VARCHAR(8) NOT NULL,
    "TIMES" VARCHAR(4) NOT NULL,
    "LECTURE_INFO" VARCHAR(8) NOT NULL
);');
INSERT INTO MY_TABLE(SCRIPT) VALUES ('ALTER TABLE "PUBLIC"."LECTURE_TIME" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_EAB" PRIMARY KEY("ID");');
INSERT INTO MY_TABLE(SCRIPT) VALUES ('-- 0 +/- SELECT COUNT(*) FROM PUBLIC.LECTURE_TIME;');
INSERT INTO MY_TABLE(SCRIPT) VALUES ('CREATE CACHED TABLE "PUBLIC"."REPORT_BOX"(
    "ID" VARCHAR(8) NOT NULL,
    "LECTURE_TIME_ID" VARCHAR(8) NOT NULL,
    "BOX_NAME" VARCHAR(100) NOT NULL,
    "LIMIT_TIME" TIMESTAMP NOT NULL,
    "START_TIME" TIMESTAMP NOT NULL,
    "CONTENT" VARCHAR(500) NOT NULL
);');
INSERT INTO MY_TABLE(SCRIPT) VALUES ('ALTER TABLE "PUBLIC"."REPORT_BOX" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("ID");');
INSERT INTO MY_TABLE(SCRIPT) VALUES ('-- 0 +/- SELECT COUNT(*) FROM PUBLIC.REPORT_BOX;');
INSERT INTO MY_TABLE(SCRIPT) VALUES ('CREATE CACHED TABLE "PUBLIC"."TODO"(
    "ID" VARCHAR(8) NOT NULL,
    "TODO_NAME" VARCHAR(100) NOT NULL,
    "TODO_CONTENT" VARCHAR(500) NOT NULL,
    "LIMIT_TIME" TIMESTAMP NOT NULL,
    "ACCOUNT_ID" VARCHAR(8) NOT NULL,
    "TYPE" VARCHAR(8) NOT NULL
);');
INSERT INTO MY_TABLE(SCRIPT) VALUES ('ALTER TABLE "PUBLIC"."TODO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");');
INSERT INTO MY_TABLE(SCRIPT) VALUES ('-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TODO;');
INSERT INTO MY_TABLE(SCRIPT) VALUES ('CREATE CACHED TABLE "PUBLIC"."NOTICE"(
    "ID" VARCHAR(8) NOT NULL,
    "ACCOUNT_ID" VARCHAR(8) NOT NULL,
    "TODO_CONFIG" VARCHAR(16) NOT NULL,
    "DUE_DATE" TIMESTAMP NOT NULL
);');
INSERT INTO MY_TABLE(SCRIPT) VALUES ('ALTER TABLE "PUBLIC"."NOTICE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("ID");');
INSERT INTO MY_TABLE(SCRIPT) VALUES ('-- 0 +/- SELECT COUNT(*) FROM PUBLIC.NOTICE;');
INSERT INTO MY_TABLE(SCRIPT) VALUES ('ALTER TABLE "PUBLIC"."CREDIT_STATUS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_798" FOREIGN KEY("LECTURE_INFO_ID") REFERENCES "PUBLIC"."LECTURE_INFO"("ID") ON UPDATE CASCADE NOCHECK;');
INSERT INTO MY_TABLE(SCRIPT) VALUES ('ALTER TABLE "PUBLIC"."NOTICE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_89" FOREIGN KEY("ACCOUNT_ID") REFERENCES "PUBLIC"."ACCOUNT"("ID") ON UPDATE CASCADE NOCHECK;');
INSERT INTO MY_TABLE(SCRIPT) VALUES ('ALTER TABLE "PUBLIC"."LECTURE_TIME" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_EAB1" FOREIGN KEY("LECTURE_INFO_ID") REFERENCES "PUBLIC"."LECTURE_INFO"("ID") ON UPDATE CASCADE NOCHECK;');
INSERT INTO MY_TABLE(SCRIPT) VALUES ('ALTER TABLE "PUBLIC"."CREDIT_STATUS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_79" FOREIGN KEY("ID") REFERENCES "PUBLIC"."ACCOUNT"("ID") ON UPDATE CASCADE NOCHECK;');
INSERT INTO MY_TABLE(SCRIPT) VALUES ('ALTER TABLE "PUBLIC"."TODO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_27" FOREIGN KEY("ACCOUNT_ID") REFERENCES "PUBLIC"."ACCOUNT"("ID") ON UPDATE CASCADE NOCHECK;');
INSERT INTO MY_TABLE(SCRIPT) VALUES ('ALTER TABLE "PUBLIC"."REPORT_BOX" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_90" FOREIGN KEY("LECTURE_TIME_ID") REFERENCES "PUBLIC"."LECTURE_TIME"("ID") ON UPDATE CASCADE NOCHECK;');